### ISSUE TITLE
Chewie Issue

### ISSUE THREAD

**Issue by krishnakanthpps** [GhoudanAyoub/live365#3]
Hey

Great work. And I was trying to run locally. 

I get this error.

/E:/flutter_stable/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:83:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/E:/flutter_stable/flutter/packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^^^^^^^^
/E:/flutter_stable/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.10/lib/src/chewie_player.dart:276:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/E:/flutter_stable/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(_ChewieControllerProvider)

Here is my flutter and Dart version. There are some breaking changes that happened in Flutter and Dart which might be the cause of this issue. 

√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.0.3 at E:\flutter_stable\flutter
    • Framework revision 4d7946a68d (28 hours ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

**Comment by GhoudanAyoub** [comment]
I'm Using Flutter 1.22.6 • channel stable 
i'll update to  new version and commit after
meanwhile try  using this  version

**Comment by krishnakanthpps** [comment]
yea. Had to downgrade to figure it out. Thank you for the response.
